#!/bin/bash
input="./adresses"
while IFS= read -r line
do
	echo "Downloading $line :"
	wget $line
	num=$(echo $line | egrep -o "[0-9]*$")
	mkdir "${num}_dir"
	cat $num | egrep -o "href=\"/bitstream[^\"]*\"" | sed "s/href=\"//g" | sed "s/\"$//g" | sed "s/^/https\:\/\/tspace\.library\.utoronto\.ca/g" > "${num}_links"
	input2="${num}_links"
	while IFS2= read -r line2
	do
		echo "Downloading $line2 :"
		filename=$(echo $line2 | egrep -o "/[^/]*$" | sed "s/^\///g")
		wget -O"${num}_dir/${filename}" $line2
	done < "$input2"
done < "$input"
